Add phpcs code adjustments
xwp/pwa-wp pull request #291
Opened 2020-06-05 14:50 UTC by avargaz

Attend some comments from the PHPCS, according to `WordPress-VIP-Go` and `WordPressVIPMinimum` standards.

2020-06-05 15:20 UTC, avargaz commented
@googlebot I signed it!

2020-06-06 04:34 UTC, westonruter requested changes

2020-06-06 04:34 UTC, westonruter commented on wp-includes/class-wp-https-ui.php
> +			$url .= wp_unslash( sanitize_text_field( $_SERVER['REQUEST_URI'] ) );
I don't think this should be done. Core doesn't do it, for example. You can search core for `wp_unslash.+?REQUEST_URI` and find many such examples:

```
src/wp-activate.php:23:list( $activate_path ) = explode( '?', wp_unslash( $_SERVER['REQUEST_URI'] ) );
src/wp-admin/widgets.php:400:					'return' => urlencode( remove_query_arg( wp_removable_query_args(), wp_unslash( $_SERVER['REQUEST_URI'] ) ) ),
src/wp-admin/edit-comments.php:129:	wp_redirect( remove_query_arg( array( '_wp_http_referer', '_wpnonce' ), wp_unslash( $_SERVER['REQUEST_URI'] ) ) );
src/wp-admin/network/user-new.php:85:				$edit_link = esc_url( add_query_arg( 'wp_http_referer', urlencode( wp_unslash( $_SERVER['REQUEST_URI'] ) ), get_edit_user_link( $user_id_new ) ) );
src/wp-admin/nav-menus.php:622:						'return' => urlencode( remove_query_arg( wp_removable_query_args(), wp_unslash( $_SERVER['REQUEST_URI'] ) ) ),
src/wp-admin/includes/class-wp-users-list-table.php:445:			$edit_link = esc_url( add_query_arg( 'wp_http_referer', urlencode( wp_unslash( $_SERVER['REQUEST_URI'] ) ), get_edit_user_link( $user_object->ID ) ) );
src/wp-admin/includes/theme.php:651:						'return' => urlencode( esc_url_raw( remove_query_arg( wp_removable_query_args(), wp_unslash( $_SERVER['REQUEST_URI'] ) ) ) ),
src/wp-admin/includes/class-wp-ms-users-list-table.php:273:			$edit_link = esc_url( add_query_arg( 'wp_http_referer', urlencode( wp_unslash( $_SERVER['REQUEST_URI'] ) ), get_edit_user_link( $user->ID ) ) );
src/wp-admin/includes/class-wp-ms-users-list-table.php:504:			$edit_link       = esc_url( add_query_arg( 'wp_http_referer', urlencode( wp_unslash( $_SERVER['REQUEST_URI'] ) ), get_edit_user_link( $user->ID ) ) );
src/wp-admin/includes/class-wp-ms-users-list-table.php:509:			$actions['delete'] = '<a href="' . esc_url( network_admin_url( add_query_arg( '_wp_http_referer', urlencode( wp_unslash( $_SERVER['REQUEST_URI'] ) ), wp_nonce_url( 'users.php', 'deleteuser' ) . '&amp;action=deleteuser&amp;id=' . $user->ID ) ) ) . '" class="delete">' . __( 'Delete' ) . '</a>';
src/wp-admin/edit-tags.php:75:	$referer = wp_unslash( $_SERVER['REQUEST_URI'] );
src/wp-admin/edit-tags.php:212:	$location = remove_query_arg( array( '_wp_http_referer', '_wpnonce' ), wp_unslash( $_SERVER['REQUEST_URI'] ) );
src/wp-admin/users.php:88:	$referer = '<input type="hidden" name="wp_http_referer" value="' . esc_attr( wp_unslash( $_SERVER['REQUEST_URI'] ) ) . '" />';
src/wp-admin/users.php:455:			wp_redirect( remove_query_arg( array( '_wp_http_referer', '_wpnonce' ), wp_unslash( $_SERVER['REQUEST_URI'] ) ) );
src/wp-admin/users.php:504:									urlencode( wp_unslash( $_SERVER['REQUEST_URI'] ) ),
src/wp-admin/menu.php:190:	$customize_url            = add_query_arg( 'return', urlencode( remove_query_arg( wp_removable_query_args(), wp_unslash( $_SERVER['REQUEST_URI'] ) ) ), 'customize.php' );
src/wp-admin/upload.php:210:	wp_redirect( remove_query_arg( array( '_wp_http_referer', '_wpnonce' ), wp_unslash( $_SERVER['REQUEST_URI'] ) ) );
src/wp-admin/plugin-install.php:31:	$location = remove_query_arg( '_wp_http_referer', wp_unslash( $_SERVER['REQUEST_URI'] ) );
src/wp-admin/user-new.php:297:				$edit_link = esc_url( add_query_arg( 'wp_http_referer', urlencode( wp_unslash( $_SERVER['REQUEST_URI'] ) ), get_edit_user_link( $user_id_new ) ) );
src/wp-admin/edit.php:211:	wp_redirect( remove_query_arg( array( '_wp_http_referer', '_wpnonce' ), wp_unslash( $_SERVER['REQUEST_URI'] ) ) );
src/wp-admin/admin.php:50:		wp_redirect( admin_url( 'upgrade.php?_wp_http_referer=' . urlencode( wp_unslash( $_SERVER['REQUEST_URI'] ) ) ) );
src/wp-admin/link-manager.php:43:	wp_redirect( remove_query_arg( array( '_wp_http_referer', '_wpnonce' ), wp_unslash( $_SERVER['REQUEST_URI'] ) ) );
src/wp-includes/functions.php:1838:	$referer_field = '<input type="hidden" name="_wp_http_referer" value="' . esc_attr( wp_unslash( $_SERVER['REQUEST_URI'] ) ) . '" />';
src/wp-includes/functions.php:1863:		$ref = 'previous' == $jump_back_to ? wp_get_referer() : wp_unslash( $_SERVER['REQUEST_URI'] );
src/wp-includes/functions.php:1888:	if ( $ref && wp_unslash( $_SERVER['REQUEST_URI'] ) !== $ref && home_url() . wp_unslash( $_SERVER['REQUEST_URI'] ) !== $ref ) {
src/wp-includes/feed.php:626:	return set_url_scheme( 'http://' . $host['host'] . wp_unslash( $_SERVER['REQUEST_URI'] ) );
src/wp-includes/class-wp-customize-manager.php:2096:		$self_url           = empty( $_SERVER['REQUEST_URI'] ) ? home_url( '/' ) : esc_url_raw( wp_unslash( $_SERVER['REQUEST_URI'] ) );
src/wp-includes/cron.php:678:		wp_redirect( add_query_arg( 'doing_wp_cron', $doing_wp_cron, wp_unslash( $_SERVER['REQUEST_URI'] ) ) );
src/wp-login.php:896:		list( $rp_path ) = explode( '?', wp_unslash( $_SERVER['REQUEST_URI'] ) );
```

So this should have the relevant sanitization rule ignored from PHPCS.

2020-06-06 04:34 UTC, westonruter commented on wp-includes/class-wp-service-workers.php
> +		$etag_header = isset( $_SERVER['HTTP_IF_NONE_MATCH'] ) ? trim( sanitize_text_field( $_SERVER['HTTP_IF_NONE_MATCH'] ) ) : false;
This is unnecessary as the value is being used entirely as part of a comparison. And core is not doing this:

```
src/wp-admin/load-styles.php:47:if ( isset( $_SERVER['HTTP_IF_NONE_MATCH'] ) && stripslashes( $_SERVER['HTTP_IF_NONE_MATCH'] ) === $wp_version ) {
src/wp-admin/load-scripts.php:48:if ( isset( $_SERVER['HTTP_IF_NONE_MATCH'] ) && stripslashes( $_SERVER['HTTP_IF_NONE_MATCH'] ) === $wp_version ) {
src/wp-includes/class-wp.php:461:			if ( isset( $_SERVER['HTTP_IF_NONE_MATCH'] ) ) {
src/wp-includes/class-wp.php:462:				$client_etag = wp_unslash( $_SERVER['HTTP_IF_NONE_MATCH'] );
src/wp-includes/ms-files.php:65:$client_etag = isset( $_SERVER['HTTP_IF_NONE_MATCH'] ) ? stripslashes( 
 $_SERVER['HTTP_IF_NONE_MATCH'] ) : false;
```

What is missing however is `wp_unslash()` and the variable name is wrong:

```suggestion
		$if_none_match = isset( $_SERVER['HTTP_IF_NONE_MATCH'] ) ? trim( wp_unslash( $_SERVER['HTTP_IF_NONE_MATCH'] ) ) : false;
```

2020-06-06 04:34 UTC, westonruter commented on wp-includes/class-wp-service-workers.php
>  		@header( "ETag: $file_hash" ); // phpcs:ignore Generic.PHP.NoSilencedErrors.Discouraged, WordPress.PHP.NoSilencedErrors.Discouraged
Just noticed this needs to be quoted per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#Directives):

```suggestion
		$etag      = sprintf( '"%s"', $file_hash );
		@header( "ETag: $etag" ); // phpcs:ignore Generic.PHP.NoSilencedErrors.Discouraged, WordPress.PHP.NoSilencedErrors.Discouraged
```

2020-06-06 04:34 UTC, westonruter commented on wp-includes/class-wp-service-workers.php
>  		if ( $file_hash === $etag_header ) {
```suggestion
		if ( $if_none_match === $etag ) {
```

2020-06-06 04:34 UTC, westonruter commented on wp-includes/class-wp-service-workers.php
>  		if ( $file_hash === $etag_header ) {
For more on what should be done here, refer to what core is doing: https://github.com/WordPress/wordpress-develop/blob/803eab428d54755acf83403a49bb1cb9c3663c13/src/wp-includes/class-wp.php#L456-L476

2020-06-06 04:35 UTC, westonruter commented on wp-includes/class-wp-https-ui.php
> +					<li><a href="<?php echo esc_url( $url ); ?>"><?php echo esc_html( $truncated_url ); ?></a></li>
Good catch on this and the instance below!

2020-06-06 04:38 UTC, westonruter requested changes

2020-06-06 04:38 UTC, westonruter commented on wp-includes/service-workers.php
> +	if ( isset( $_COOKIE['wordpress_sw_installed'] ) ) {  // phpcs:ignore WordPressVIPMinimum.Variables.RestrictedVariables.cache_constraints___COOKIE
The `WordPressVIPMinimum` ruleset is not part of this project, so it doesn't make sense to reference it. If this is causing problems for your install, I suggest ignoring it in a custom ruleset on your end.

```suggestion
	if ( isset( $_COOKIE['wordpress_sw_installed'] ) ) {
```

2020-06-06 04:38 UTC, westonruter commented on wp-includes/template.php
> +		$output = '<details id="error-details"><summary>' . esc_html__( 'More Details', 'pwa' ) . '</summary>{{{error_details_iframe}}}</details>'; // phpcs:ignore WordPressVIPMinimum.Security.Mustache.Out
Ditto with above in regards to `WordPressVIPMinimum`.

```suggestion
		$output = '<details id="error-details"><summary>' . esc_html__( 'More Details', 'pwa' ) . '</summary>{{{error_details_iframe}}}</details>';
```

2020-06-08 19:28 UTC, westonruter approved these changes
Thanks a lot.

2020-06-08 20:06 UTC, merged

2020-06-08 20:12 UTC, avargaz commented
Thanks to you @westonruter ! You basically did everything 😄 
Cheers!